/*
-- Query: SELECT * FROM r_j_burgers.customer
LIMIT 0, 1000

-- Date: 2020-11-27 19:30
*/
INSERT INTO `` (`CustomerID`,`CustomerFirstName`,`CustomerLastName`,`CustomerStreet1`,`CustomerStreet2`,`CustomerCity`,`CustomerState`,`CustomerZip`,`CustomerPhone`,`CustomerEmail`,`CustomerOrders`,`CustomerCurrentDiscount`) VALUES (1,'Jack','Brown','2321 Jupiter Rd.',NULL,'Plano','TX','75023','9253162455','Brown.Jack@gmail.com',NULL,3);
INSERT INTO `` (`CustomerID`,`CustomerFirstName`,`CustomerLastName`,`CustomerStreet1`,`CustomerStreet2`,`CustomerCity`,`CustomerState`,`CustomerZip`,`CustomerPhone`,`CustomerEmail`,`CustomerOrders`,`CustomerCurrentDiscount`) VALUES (2,'Mike','Levy','1717 Parker Rd.',NULL,'Plano','TX','75023','9172341717','bblevy@yahoo.com',NULL,5);
INSERT INTO `` (`CustomerID`,`CustomerFirstName`,`CustomerLastName`,`CustomerStreet1`,`CustomerStreet2`,`CustomerCity`,`CustomerState`,`CustomerZip`,`CustomerPhone`,`CustomerEmail`,`CustomerOrders`,`CustomerCurrentDiscount`) VALUES (3,'Jennifer','Lowis','1344 Los Rios Ln.',NULL,'Plano','TX','75074','9144442567','jlowis@gmail.com',NULL,3);
INSERT INTO `` (`CustomerID`,`CustomerFirstName`,`CustomerLastName`,`CustomerStreet1`,`CustomerStreet2`,`CustomerCity`,`CustomerState`,`CustomerZip`,`CustomerPhone`,`CustomerEmail`,`CustomerOrders`,`CustomerCurrentDiscount`) VALUES (4,'Mike ','Proditov','1456 Coit Rd.',NULL,'Plano','TX','75075','9543171298','mpmpp@outlook.com',NULL,3);
INSERT INTO `` (`CustomerID`,`CustomerFirstName`,`CustomerLastName`,`CustomerStreet1`,`CustomerStreet2`,`CustomerCity`,`CustomerState`,`CustomerZip`,`CustomerPhone`,`CustomerEmail`,`CustomerOrders`,`CustomerCurrentDiscount`) VALUES (5,'Sy','Lee','7865 Legacy Dr.',NULL,'Plano','TX','75025','9180054335','sylee@outlook.com',NULL,3);
INSERT INTO `` (`CustomerID`,`CustomerFirstName`,`CustomerLastName`,`CustomerStreet1`,`CustomerStreet2`,`CustomerCity`,`CustomerState`,`CustomerZip`,`CustomerPhone`,`CustomerEmail`,`CustomerOrders`,`CustomerCurrentDiscount`) VALUES (6,'Lara','De Ane','7878 Blackjack St.',NULL,'Plano','TX','75074','9251789696','deAne@gmail.com',NULL,7);
INSERT INTO `` (`CustomerID`,`CustomerFirstName`,`CustomerLastName`,`CustomerStreet1`,`CustomerStreet2`,`CustomerCity`,`CustomerState`,`CustomerZip`,`CustomerPhone`,`CustomerEmail`,`CustomerOrders`,`CustomerCurrentDiscount`) VALUES (7,'Natalia','Oliveira','5653 Los Rios Ln.',NULL,'Plano','TX','75074','9876565653','noliveira@yahoo.com',NULL,7);
INSERT INTO `` (`CustomerID`,`CustomerFirstName`,`CustomerLastName`,`CustomerStreet1`,`CustomerStreet2`,`CustomerCity`,`CustomerState`,`CustomerZip`,`CustomerPhone`,`CustomerEmail`,`CustomerOrders`,`CustomerCurrentDiscount`) VALUES (8,'John','Ross','5412 Spring Creek Pkwy.',NULL,'Plano','TX','75093','9169993452','mrjohn@gmail.com',NULL,5);
INSERT INTO `` (`CustomerID`,`CustomerFirstName`,`CustomerLastName`,`CustomerStreet1`,`CustomerStreet2`,`CustomerCity`,`CustomerState`,`CustomerZip`,`CustomerPhone`,`CustomerEmail`,`CustomerOrders`,`CustomerCurrentDiscount`) VALUES (9,'Ding','Ping','6517 Legacy Dr.',NULL,'Plano','TX','75025','9186563434','dingping@outlook.com',NULL,7);
INSERT INTO `` (`CustomerID`,`CustomerFirstName`,`CustomerLastName`,`CustomerStreet1`,`CustomerStreet2`,`CustomerCity`,`CustomerState`,`CustomerZip`,`CustomerPhone`,`CustomerEmail`,`CustomerOrders`,`CustomerCurrentDiscount`) VALUES (10,'Denis','Tekhnenko','1515 Coldwater Creek Ln.',NULL,'Plano','TX','75074','9403127547','bigden@gmail.com',NULL,3);
INSERT INTO `` (`CustomerID`,`CustomerFirstName`,`CustomerLastName`,`CustomerStreet1`,`CustomerStreet2`,`CustomerCity`,`CustomerState`,`CustomerZip`,`CustomerPhone`,`CustomerEmail`,`CustomerOrders`,`CustomerCurrentDiscount`) VALUES (12,'George','Clooney','1315 Riverchase Dr','Apt 2117','Coppell','TX','75019','2148020601','jeringeorge@gmail.com',3,3);
INSERT INTO `` (`CustomerID`,`CustomerFirstName`,`CustomerLastName`,`CustomerStreet1`,`CustomerStreet2`,`CustomerCity`,`CustomerState`,`CustomerZip`,`CustomerPhone`,`CustomerEmail`,`CustomerOrders`,`CustomerCurrentDiscount`) VALUES (13,'Willaim','Lorenza','690 Rosia St','Apt 922','Ernestine','MP','87111','8111138738','Willaim.Lorenza@gmail.com',27,3);
INSERT INTO `` (`CustomerID`,`CustomerFirstName`,`CustomerLastName`,`CustomerStreet1`,`CustomerStreet2`,`CustomerCity`,`CustomerState`,`CustomerZip`,`CustomerPhone`,`CustomerEmail`,`CustomerOrders`,`CustomerCurrentDiscount`) VALUES (14,'Milford','West','145 Rosella St','Apt 20','Park','NY','66616','4669710639','Milford.West@gmail.com',13,0);
INSERT INTO `` (`CustomerID`,`CustomerFirstName`,`CustomerLastName`,`CustomerStreet1`,`CustomerStreet2`,`CustomerCity`,`CustomerState`,`CustomerZip`,`CustomerPhone`,`CustomerEmail`,`CustomerOrders`,`CustomerCurrentDiscount`) VALUES (15,'Ray','Katharine','101 Gustav St','Apt 3','Omie','MN','83396','4112323167','Ray.Katharine@gmail.com',22,0);
